### PR TITLE
[#271] Attempt to build an nginx container with the client app

### PR DESCRIPTION
**Pull request by iperdomo**

### CODE REVIEW

**Comment by orifito** [comment]
@iperdomo why don't we use [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy)?

**Comment by iperdomo** [comment]
@orifito because is way too complex for what we need (imho)

**Comment by iperdomo** [comment]
We just need something that serve some static files (`index.html and proxies some requests to `/api/*` ...

**Comment by orifito** [comment]
@iperdomo yeah, I understand your point. However, I don't find this too complex: https://github.com/akvo/akvo-provisioning/tree/develop/docker/cartodb/lb
Anyway, let's just be pragmatic :+1:

**Pull request closed without merging**
